trigger: none
pr:
  branches:
    include:
      - main
      - build-pipeline

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Build.Repository.LocalPath " $(Build.Repository.LocalPath)
      echo "Build.Repository.ID " $(Build.Repository.ID)
      echo "Build.Repository.Name " $(Build.Repository.Name)
      echo "..."
      echo "System Vars"
      echo ".. ."
      echo "System.PullRequest.IsFork" $(System.PullRequest.IsFork)
      echo "System.PullRequest.PullRequestId" $(System.PullRequest.PullRequestId)
      echo "System.PullRequest.PullRequestNumber" $(System.PullRequest.PullRequestNumber)
      echo "System.PullRequest.SourceBranch" $(System.PullRequest.SourceBranch)
      echo "System.PullRequest.SourceRepositoryURI" $(System.PullRequest.SourceRepositoryURI)
      echo "System.PullRequest.TargetBranch" $(System.PullRequest.TargetBranch)
